[INFO              ] Logger: Record log in /Applications/Kivy.app/Contents/Resources/.kivy/logs/kivy_16-05-16_9.txt
[INFO              ] Kivy: v1.9.1-dev0
[INFO              ] Python: v2.7.10 (default, Jul 14 2015, 19:46:27) 
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.39)]
[INFO              ] Factory: 179 symbols loaded
[INFO              ] Image: Providers: img_tex, img_imageio, img_dds, img_gif, img_sdl2 (img_pil, img_ffpyplayer ignored)
[INFO              ] Text: Provider: sdl2
[WARNING           ] stderr: Traceback (most recent call last):
[WARNING           ] stderr:   File "main.py", line 4, in <module>
[WARNING           ] stderr:     from ConnectFour import *
[WARNING           ] stderr:   File "/Users/nico/packer/pack/connectfour/ConnectFour.py", line 10, in <module>
[WARNING           ] stderr:     from Mechanics import *
[WARNING           ] stderr:   File "/Users/nico/packer/pack/connectfour/Mechanics.py", line 27
[WARNING           ] stderr:     return (S[S==0].size == 0)
[WARNING           ] stderr:                              ^
[WARNING           ] stderr: IndentationError: unindent does not match any outer indentation level
